### ISSUE TITLE
can not open “luajit-5.1.lib”	synthlike	

### ISSUE THREAD

**Issue by dd123-a** [numpad/ecs-sandbox#64]
I'm not sure why this library is missing. Are there more detailed build instructions available? I'm very interested in this project.

**Comment by dd123-a** [comment]
"public: __cdecl fmt::v10::detail::value<class fmt::v10::basic_format_context<class fmt::v10::appender,char> >::value<class fmt::v10::basic_format_context<class fmt::v10::appender,char> >(struct fmt::v10::detail::unformattable_pointer)" (??0?$value@V?$basic_format_context@Vappender@v10@fmt@@D@v10@fmt@@@detail@v10@fmt@@QEAA@Uunformattable_pointer@123@@Z)，函数 "void __cdecl fmt::v10::print<char [24],unsigned char const *,unsigned char const *,0>(class fmt::v10::text_style const &,char const (&)[24],unsigned char const * const &,unsigned char const * const &)" (??$print@$$BY0BI@DPEBEPEBE$0A@@v10@fmt@@YAXAEBVtext_style@01@AEAY0BI@$$CBDAEBQEBE2@Z) 中引用了该符号	
 
 get a new problem

**Comment by dd123-a** [comment]
constexpr bool formattable_pointer =
      !std::is_same<arg_type, unformattable_pointer>::value;
  if (!formattable_pointer) {
    return static_cast<void*>(nullptr);
  }我修改了这部分逻辑，使得它可以编译通过，但是得到的exe无法运行

**Comment by dd123-a** [comment]
他说没有install文件，无法运行，但在说明文档中没有对这部分内容的描述

**Comment by dd123-a** [comment]
fuck you，waste my time

**Comment by dd123-a** [comment]
you really run this project in your local env,why i need to check alot of things

**Comment by numpad** [comment]
Hi :) I've just noticed that I'm not receiving GitHub notifications, so I apologize for my delayed response.

I've pushed some minor changes to `develop` that may resolve the issues you've experienced with LuaJIT and the call to fmt::print(). However I currently lack the spare time and interest to look into this more thoroughly, sorry!

This being a project for learning purposes, many things are really flaky. I didn't have the chance to test this on other devices apart from my computer.

**Comment by dd123-a** [comment]
I've re-pulled the project and ran it according to the README, and now the error it's showing is:

Error Description	Project	File	Line	Status Hidden
Unable to open include file: "luajit-2.1/lua.hpp": No such file or directory	synthlike	-	-	Hidden

Error Description	Project	File	Line	Status Hidden
"AssetManager::loadModel" must return a value	synthlike	ecs-sandbox\src\core\Assets\AssetManager.cpp	183

**Comment by dd123-a** [comment]
In fact, this project should not have so many errors; perhaps you have made numerous changes but haven't updated them on GitHub. You could try releasing an updated executable for the game, or reuploading the project to GitHub. Thank you for your response.

**Comment by dd123-a** [comment]
In fact, if it's only regarding this issue, I have already resolved it. The current problem is not related to this issue, and I will close it and open a new one. The issue now is that after I have ruled out most of the problems, the program runs without any graphics; it only has a black background and the window will close automatically.
